version: "3.9"
services:

  mongo:
    image: mongo:4.4.17
    container_name: mongo
    restart: always
    command: ['--logpath', '/var/log/mongodb/mongo.log']
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - ton-fun-parser-mongo-db:/data/db
      - ton-fun-parser-mongo-log:/var/log/mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  mongo-express:
    image: mongo-express:1.0.0-alpha
    restart: always
    ports:
      - ${MONGO_EXPRESS_PORT}:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017

volumes:
  ton-fun-parser-mongo-db:
  ton-fun-parser-mongo-log: