name: Build and deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  HOST: ton-lotto.fun

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tags
        id: meta
        uses: docker/metadata-action@v4.1.1
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            latest
            type=sha

      - name: Build and push
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ env.HOST }}
          port: 22
          username: root
          key: ${{ secrets.SSH_DEPLOY_PRIVATE_KEY}}
          source: docker-compose.yaml,.env.prod
          target: /srv/${{ github.repository }}
          overwrite: true

      - name: Deployment
        uses: appleboy/ssh-action@v0.1.5
        with:
          script: |
            cd /srv/${{ github.repository }}
            echo ${{ secrets.GITHUB_TOKEN }} | docker login https://ghcr.io --username ${{ github.repository_owner }} --password-stdin
            export MONGO_INITDB_ROOT_PASSWORD=${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}
            docker compose -f docker-compose.yaml --env-file .env.prod pull
            docker compose -f docker-compose.yaml --env-file .env.prod down
            docker compose -f docker-compose.yaml --env-file .env.prod up -d
          host: ${{ env.HOST }}
          port: 22
          username: root
          key: ${{ secrets.SSH_DEPLOY_PRIVATE_KEY }}
